version: '3.8'

services:
  server:
    image: astra-zabbix-server-pgsql:6.0
    hostname: zabbix-server
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      ZBX_STATSALLOWEDIP: zabbix-agent
    ports:
      - "10051:10051"
    depends_on:
      - postgres

  agent:
    image: astra-zabbix-agent:6.0
    hostname: zabbix-agent
    build:
      context: ./agent
      dockerfile: Dockerfile
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_PORT: 10051
      ZBX_HOSTNAME: zabbix-agent
    ports:
      - "10050:10050"
    depends_on:
      - server

  frontend:
    image: astra-zabbix-frontend-unit-pgsql:6.0
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_PORT: 10051
      # В соответствии с указанным ZBX_HOSTNAME у агента
      ZBX_SERVER_NAME: zabbix-agent
      DB_SERVER_HOST: postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - server
      - agent

  postgres:
    image: astra-postgres:11
    build:
      context: ../postgres
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
    volumes:
      - ./zabbix-data/postgres:/var/lib/postgresql/data